// Every line of player-facing text in one place, so a test can scan it (no em or en dashes).

export const COPY = {
  title: { a: 'SPIDER-MAN', b: 'WEB OF INK' },
  subtitle: 'Swing test build. Hold swing and the webs chain on their own. Steer, time your releases and fly.',
  disclaimer: 'Unofficial fan game. Not affiliated with or endorsed by Marvel or Sony. Spider-Man and related characters are trademarks of Marvel. Made for fun, never sold.',
  buttons: { play: 'FREE SWING', settings: 'SETTINGS', controls: 'CONTROLS', resume: 'RESUME', restart: 'BACK TO THE ROOFTOP', quit: 'QUIT TO TITLE', back: 'BACK', reset: 'RESET TO DEFAULTS' },
  pause: 'PAUSED',
  clickToPlay: 'CLICK TO SWING',
  noAnchor: 'NOTHING TO WEB',
  lowPower: 'Your browser is holding the game at 30 frames a second (Low Power Mode or Energy Saver). Plug in, or turn that mode off, for a smoother swing.',
  ok: 'Got it',
  // First-play tips, in order. Each one leaves when you do the thing it asks.
  tips: [
    { id: 'swing', text: 'Run off the edge and hold <kbd>{swing}</kbd>. Keep holding and the webs chain on their own. Steer with the mouse or <kbd>{move}</kbd>.', done: 'release' },
    { id: 'perfect', text: 'Let go of <kbd>{swing}</kbd> just after the bottom of a swing, on the way up, for a perfect release boost.', done: 'perfect' },
    { id: 'jump', text: 'Tap <kbd>{jump}</kbd> mid-swing to leap off the web, high and fast.', done: 'swingJump' },
    { id: 'zip', text: 'Look at a ledge and press <kbd>{zip}</kbd> to zip to it. Press <kbd>{jump}</kbd> the moment you land to launch.', done: 'launch' },
    { id: 'wall', text: 'Swing into a wall to run along it. Hold <kbd>{swing}</kbd> to run up, <kbd>{jump}</kbd> to kick off.', done: 'wallJump' },
    { id: 'wings', text: 'In the air, press and hold <kbd>{jump}</kbd> for web wings. Hold <kbd>{dive}</kbd> to dive. Press <kbd>{help}</kbd> for all controls.', done: 'wings' },
  ],
  help: {
    title: 'CONTROLS',
    rows: [
      ['{move}', 'Move and steer (swings follow where you point)'],
      ['Mouse', 'Look'],
      ['{swing}', 'Hold in the air: swing (webs keep chaining while held). Let go just past the bottom for a boost. Ground: parkour run. Wall: run up'],
      ['{jump}', 'Jump. Swinging: swing-jump. In the air: web wings'],
      ['{zip}', 'Web zip to where you look. Then {jump} to launch'],
      ['{dive}', 'Dive (hold in the air)'],
      ['{pause}', 'Pause and settings'],
    ],
  },
  settings: {
    title: 'SETTINGS',
    gravity: ['Gravity', 'Comic is twice real gravity: snappier arcs. Real is 9.81 m/s squared.'],
    gravityValues: { comic: 'Comic (2g)', real: 'Real (1g)' },
    assist: ['Swing assist', 'Only changes which real anchor the web aims for. It never moves you.'],
    assistValues: { off: 'Off', normal: 'Normal', high: 'High' },
    toggle: ['Swing button', 'Hold to stay on the web, or press once to grab and again to let go.'],
    toggleValues: { false: 'Hold', true: 'Toggle' },
    sensitivity: ['Mouse sensitivity'],
    invertY: ['Invert vertical look'],
    fov: ['Field of view'],
    speedLines: ['Speed lines'],
    cameraShake: ['Camera shake'],
    quality: ['Graphics'],
    qualityValues: { high: 'High', medium: 'Medium', low: 'Low' },
    renderScale: ['Render scale'],
    dynamicRes: ['Dynamic resolution', 'Drops resolution a little when the frame rate dips.'],
    showFps: ['Show frame rate'],
    master: ['Master volume'],
    sfx: ['Effects volume'],
    sections: { move: 'SWINGING', camera: 'CAMERA', video: 'GRAPHICS', audio: 'SOUND' },
  },
  controls: {
    title: 'CONTROLS',
    keyboard: 'KEYBOARD AND MOUSE',
    gamepad: 'GAMEPAD',
    pressKey: 'Press a key',
    padRows: [
      ['Left stick', 'Move'],
      ['Right stick', 'Look'],
      ['RT / R2 (hold)', 'Swing (chains while held), parkour run, wall run'],
      ['A / Cross', 'Jump, swing-jump, web wings'],
      ['LT + RT / L2 + R2', 'Web zip'],
      ['B / Circle (hold)', 'Dive'],
      ['Start / Options', 'Pause'],
      ['Back / Share', 'Controls help'],
    ],
  },
};
