// Every line of player-facing text in one place, so a test can scan it (no em or en dashes).

export const COPY = {
  title: { a: 'SPIDER-MAN', b: 'WEB OF INK' },
  subtitle: 'The city needs a hero. Aim the crosshair at a building, hold swing, let go and aim the next one.',
  disclaimer: 'Unofficial fan game. Not affiliated with or endorsed by Marvel or Sony. Spider-Man and related characters are trademarks of Marvel. Made for fun, never sold.',
  roster: { title: 'CHARACTERS', heroes: 'HEROES', villains: 'VILLAINS', playing: 'Playing', play: 'Play', locked: 'Finish the story to play everyone in free roam (everyone is open in multiplayer).' },
  mp: {
    title: 'MULTIPLAYER', blurb: 'One shared city for up to five friends. Everyone can play anyone, with everything unlocked. Your story save is never touched.',
    name: 'Your name', namePh: 'Name', codePh: 'CODE', pick: 'PLAY AS', create: 'CREATE WORLD', join: 'JOIN', or: 'or join with a code:',
    connecting: 'Connecting...', advanced: 'Relay server', relay: 'Relay address', ended: 'The host ended the world.',
    worldTitle: 'YOUR WORLD', code: 'JOIN CODE', share: 'Send this code to your friends. They pick MULTIPLAYER, type it in and press JOIN.',
    players: 'PLAYERS', you: 'you', away: 'reconnecting', hostTag: 'HOST', modes: 'START A ROUND', hostRuns: 'The host starts rounds.',
    start: 'Start', fairRace: 'RACE WITH A FAIR SPEED CAP', end: 'END WORLD', leave: 'LEAVE',
    chatPh: 'Say something (Enter to send)',
    quick: ['On my way!', 'Over here!', 'Need a hand!', 'Nice one!', 'Race you there!', 'Watch out!', 'Wait for me!', 'Thwip!'],
  },
  buttons: { multiplayer: 'MULTIPLAYER', roster: 'CHARACTERS', progress: 'SKILLS AND SUITS', play: 'FREE SWING', story: 'STORY', tracker: 'CITY PROGRESS', photo: 'PHOTO MODE', gauntlet: 'VILLAIN GAUNTLET', nights: 'CRIME NIGHTS', settings: 'SETTINGS', controls: 'CONTROLS', resume: 'RESUME', restart: 'BACK TO THE ROOFTOP', quit: 'QUIT TO TITLE', back: 'BACK', reset: 'RESET TO DEFAULTS' },
  pause: 'PAUSED',
  story: {
    comicHelp: 'Click or press Space to read on. Esc skips the scene.',
    onAir: 'ON THE AIR',
    objective: 'OBJECTIVE',
    missionDone: 'MISSION COMPLETE',
    bossDown: 'BOSS DEFEATED',
    retry: 'TRY AGAIN',
    generator: 'GENERATOR',
    ghost: 'GHOST!',
    credits: [
      { h: true, text: 'SPIDER-MAN: WEB OF INK' },
      { text: 'An unofficial fan game' },
      { h: true, text: 'Made by' },
      { text: 'Krishn Gohel' },
      { h: true, text: 'Story, swinging, ink and code' },
      { text: 'Built with Three.js, a lot of rope physics and a lot of comic pages' },
      { h: true, text: 'Models' },
      { text: 'Hero body and animations: Quaternius (CC0)' },
      { text: '"The Amazing Spider-Man 2 Spider-Man" suit model by fredbear1211 on Sketchfab (sketchfab.com/fredbear1211), CC BY 4.0, fitted to the game skeleton' },
      { text: 'Motion capture: Mixamo (Adobe), retargeted to the game skeleton' },
      { h: true, text: 'Music' },
      { text: 'Battle Theme A by cynicmusic (CC0)' },
      { text: 'Urban Theme by MintoDog (CC0)' },
      { text: 'Night Escape by Agecaf (CC0)' },
      { text: 'Chill lofi inspired by omfgdude (CC0)' },
      { text: 'Fight in the City by Umplix (CC0)' },
      { text: 'Epic Boss Battle by Juhani Junkala (CC0)' },
      { text: 'All found on OpenGameArt.org' },
      { h: true, text: 'Thanks' },
      { text: 'Everyone who swung through this city' },
      { text: 'Spider-Man and related characters are trademarks of Marvel. This game is not affiliated with or endorsed by Marvel or Sony. Made for fun, never sold.' },
      { h: true, text: 'The city is yours.' },
    ],
    alarm: 'THEY SAW YOU',
    takedown: { ground: '{attack} TAKEDOWN', perch: '{attack} DROP ON HIM', hang: '{attack} HAUL HIM UP' },
    getThere: 'Get there:',
    nextMission: 'Next mission',
    cards: {
      act: { sub: 'A new chapter begins.' },
      actEnd: { end: 'complete', sub: 'To be continued.' },
      free: { top: 'Prologue complete', title: 'The city is yours', sub: 'Swing anywhere between missions. The next mission is marked on the map.' },
    },
    tips: {
      swing: 'Hold {swing} with the crosshair on a building to swing.',
      jump: 'Tap {jump} near the bottom of a swing to launch forward.',
      zip: 'Press {zip} to zip to a ledge or a point.',
      wall: 'Run into a wall to run up it. {zip} at a ledge pulls you up.',
      attack: 'Press {attack} to punch. Keep hitting to build a combo.',
      dodge: 'When your spider-sense flashes, press {dive} to dodge.',
      web: 'Press {web} to web up enemies. Webbed enemies are out of the fight.',
      freeroam: 'Hold {emote} for the emote wheel. Press {photoMode} for photo mode.',
      requests: 'New Yorkers with a ! over them need a hand. Walk up and press {hang} to talk.',
      yank: '{hang} on a target to web yank it.',
      finisher: 'With full focus, tap {finisher} for a finisher. Hold it to heal.',
      cover: "Shocker's blasts cannot go through buildings. Use them as cover.",
      yankProp: 'Aim at a crate and press {hang} to yank it into him.',
      chase: 'Stay close and press {web} to hit him with webs.',
      yankDive: 'When he dives, press {hang} to web yank him out of the sky.',
      charge: 'Dodge his charge with {dive} so he hits a wall instead.',
    relay: 'Charged, he cannot be hurt. Get to a relay box and hit it to short it and drain him. Up on a chimney, yank its relay with {hang}.',
    backfire: 'Perfect dodge a blast with {dive} on the red flash and his gauntlets backfire.',
    venomBlast: 'Press {web} for a venom blast: it shocks everyone close to you.',
    poison: 'The poison is a clock. Perfect dodges buy you time.',
    scan: 'Press {scan} to use your spider-sense and mark the real Mysterio.',
    drones: 'The giant is a projection. Knock the projector drones out of the air.',
    parkRun: 'Few anchors in the park: zip with {zip}, run, and glide.',
    cure: 'When he slumps, web him with {web} to hold him for the cure.',
    takedown: 'Sneak up behind a guard who has not seen you and press {attack} for a silent takedown.',
    perch: 'From above (a wall, a ledge, a web hang) press {attack} to drop on a guard below.',
    sense: 'The eye over a guard fills as he notices you. Full means the alarm.',
    yankKraven: 'When the spider-sense marks him, press {hang} to yank him out of the tree.',
    hydrant: 'Break a fire hydrant (punch it, or aim and press {hang}) and soak him to mud.',
    tank: 'Aim at a water tank and press {hang} to tip it over onto the giant.',
    anger: 'The Black Suit hits much harder. It wants you to keep hitting.',
    bell: 'Aim at the bell rope and press {hang}: the sound staggers him.',
    ockGrab: 'When his arm reaches for you, dodge with {dive} or be reeled in.',
    ockBraced: 'Braced on the crown, he shrugs off blows. Yank him with {hang} to tear an arm free.',
    catch: 'Aim at MJ and press {web}. The web line takes her weight.',
    },
    slots: { ngPlus: 'NEW GAME+', title: 'STORY', slot: 'Slot', empty: 'Empty', newGame: 'NEW GAME', continue: 'CONTINUE', load: 'LOAD', confirm: 'Start over in this slot? Its story progress is replaced.', played: 'played' },
  },
  clickToPlay: 'CLICK THE GAME TO USE THE MOUSE. ESC GIVES IT BACK.',
  map: {
    close: 'CLOSE MAP',
    hint: 'Drag to move, wheel to zoom. Click to set a waypoint, click a found subway station to ride there.',
    ride: 'click to ride the subway here',
    notFound: 'find this station in the city first',
  },
  stationFound: 'SUBWAY STATION FOUND',
  progress: {
    title: 'SKILLS AND SUITS', level: 'LEVEL', points: 'skill points', learned: 'Learned', free: 'Free', locked: 'Not built',
    build: 'Build', upgrade: 'Upgrade', max: 'Top level', wear: 'Wear', wearing: 'Wearing', remove: 'Remove', equip: 'Equip', equipped: 'Equipped',
    powerLocked: 'Unlock a suit with this power', story: 'Unlocked by the story', modsNote: 'Up to three mods at a time. Removing one keeps it bought only while it is on, so choose well.',
    tabs: { skills: 'SKILLS', suits: 'SUITS', gadgets: 'GADGETS', mods: 'MODS', powers: 'POWERS' },
    trees: { webslinger: 'WEBSLINGER', defender: 'DEFENDER', innovator: 'INNOVATOR' },
  },
  combat: { gangSpotted: 'STREET GANG SPOTTED', gangBusted: 'GANG BUSTED!', defeated: 'DOWN, BUT NOT OUT', combo: 'COMBO', focus: 'FOCUS' },
  subwayTo: 'SUBWAY TO',
  noAnchor: 'MISSED',
  lowPower: 'The game is running at 30 frames a second, which usually means Low Power Mode or battery saver is on. Plug in, or turn it off in your battery settings, for a smoother swing.',
  // First-play tips, in order. Each one leaves when you do the thing it asks.
  tips: [
    { id: 'swing', text: 'Jump, then hold <kbd>{swing}</kbd> in the air to swing: the web finds a building. Let go to fly, hold again for the next web.', done: 'release' },
    { id: 'perfect', text: 'Let go of <kbd>{swing}</kbd> late in the swing, as your legs come up, for a release boost.', done: 'perfect' },
    { id: 'jump', text: 'Tap <kbd>{jump}</kbd> mid-swing to leap off the web, high and fast.', done: 'swingJump' },
    { id: 'hang', text: 'Swinging, press <kbd>{hang}</kbd> to hang on the line. <kbd>{forward}</kbd> climbs, <kbd>{back}</kbd> slides down, <kbd>{dive}</kbd> rappels. Climb to a roof edge to pull yourself up.', done: 'hang' },
    { id: 'zip', text: 'The white dot is a zip point: press <kbd>{zip}</kbd> to zip there, then <kbd>{jump}</kbd> as you land to launch. With nothing to zip to, <kbd>{zip}</kbd> is a boost.', done: 'launch' },
    { id: 'wall', text: 'Swing into a wall to run on it. Hold <kbd>{swing}</kbd> to run up, steer to run across, <kbd>{jump}</kbd> to kick off.', done: 'wallJump' },
    { id: 'wings', text: 'In the air, press and hold <kbd>{jump}</kbd> for web wings. Hold <kbd>{dive}</kbd> to dive. Press <kbd>{help}</kbd> for all controls.', done: 'wings' },
  ],
  help: {
    title: 'CONTROLS',
    rows: [
      ['{move}', 'Move and steer (swings follow where you point)'],
      ['Mouse', 'Look'],
      ['{swing}', 'Web where the crosshair points (white: in range), hold to swing, let go to fly. Let go just past the bottom for a boost. Ground: parkour run. Wall: run up'],
      ['{jump}', 'Jump (hold to go higher). Swinging: swing-jump. In the air: web wings'],
      ['{trick}', 'Air trick: flips and spins'],
      ['{zip}', 'Web zip to where you look. Then {jump} to launch'],
      ['{hang}', 'Hang on the web, swinging or aimed in the air. {forward} climbs, {back} slides, {dive} rappels, {jump} jumps off, {hang} lets go. Climb to a roof edge to pull up onto it. Hang still and you flip upside down'],
      ['{dive}', 'Dive (hold in the air). Fighting: dodge (right as the spider-sense turns red for a perfect dodge)'],
      ['{attack}', 'Attack string. Hold next to an enemy: launch him, then {attack} in the air. From afar: web strike. From above: ground slam'],
      ['Combos', 'Right after a dodge, {attack}: counter. {attack}, {attack}, a pause, {attack}: sweep. Steer away from a thug behind you and {attack}: back kick. {web} a thug out of reach, then {attack}: web pull. Combo of 10: {attack} and {web} together: web blast'],
      ['{web}', 'Web shot: three hits webs an enemy up. A webbed enemy knocked into a wall sticks to it'],
      ['{hang}', 'Near an enemy (not swinging): web yank. Pulls him in, or pulls the gun out of his hands'],
      ['{finisher}', 'Tap: finisher (one focus bar). Hold: heal (one focus bar)'],
      ['{hang}', 'Next to a webbed enemy: swing him round and throw him into the others'],
      ['{gadget}', 'Use gadget ({gadgetWheel} held: gadget wheel)'],
      ['{suitPower}', 'Suit power (once a minute)'],
      ['{scan}', 'Spider-sense scan: marks enemies and hidden things'],
      ['{photo}', 'Take a photo'],
      ['Ledges', 'Come up a little short of a roof and he grabs the edge and climbs over'],
      ['Corners', 'Swing past a building corner and the web wraps round it: you whip round with a boost'],
      ['Roof edges', 'Land near a roof edge and press {jump} straight away to launch off it'],
      ['{map}', 'City map: waypoints and subway fast travel'],
      ['{pause}', 'Pause and settings'],
    ],
  },
  settings: {
    title: 'SETTINGS',
    gravity: ['Gravity', 'Comic is twice real gravity: snappier arcs. Real is 9.81 m/s squared.'],
    gravityValues: { comic: 'Comic (2g)', real: 'Real (1g)' },
    swingAssist: ['Swing assist', 'On: the swing always finds a building above and ahead, and the crosshair still picks when it is on one. Off: webs only go where you aim, and can miss.'],
    swingAssistValues: { off: 'Off (aimed webs)', normal: 'On', high: 'Strong' },
    assist: ['Swing assist', 'Only changes which real anchor the web aims for. It never moves you.'],
    assistValues: { off: 'Off', normal: 'Normal', high: 'High' },
    toggle: ['Swing button', 'Hold to stay on the web, or press once to grab and again to let go.'],
    toggleValues: { false: 'Hold', true: 'Toggle' },
    sensitivity: ['Mouse sensitivity'],
    invertY: ['Invert vertical look'],
    invertX: ['Invert horizontal look'],
    textSize: ['Text size', 'Radio, comics, objectives and tips'],
    textSizeValues: { normal: 'NORMAL', large: 'LARGE', huge: 'HUGE' },
    colorblind: ['Colour-blind safe colours', 'Crosshair and prompts in blue and amber'],
    slowMo: ['Slow-motion assist', 'The whole game runs at three quarters speed'],
    finisherSlowmo: ['Finisher slow motion', 'A beat of slow motion when a finisher lands'],
    fov: ['Field of view'],
    speedLines: ['Speed lines'],
    soundWords: ['Sound words', 'THWIP! and friends, in comic lettering.'],
    cameraShake: ['Camera shake'],
    quality: ['Graphics'],
    qualityValues: { high: 'High', medium: 'Medium', low: 'Low' },
    renderScale: ['Render scale'],
    dynamicRes: ['Dynamic resolution', 'Drops resolution a little when the frame rate dips.'],
    showFps: ['Show frame rate'],
    showSpeed: ['Show speed'],
    difficulty: ['Difficulty', 'How hard enemies hit and how many attack at once.'],
    difficultyValues: { friendly: 'Friendly', amazing: 'Amazing', spectacular: 'Spectacular' },
    crimes: ['Street crime', 'Gangs gather on street corners in free roam.'],
    timeOfDay: ['Time of day', 'Cycle runs a full day every 24 minutes.'],
    timeValues: { cycle: 'Cycle', day: 'Day', golden: 'Golden hour', night: 'Night' },
    weather: ['Weather'],
    weatherValues: { cycle: 'Changes', clear: 'Clear', overcast: 'Overcast', rain: 'Rain' },
    master: ['Master volume'],
    music: ['Music volume'],
    sfx: ['Effects volume'],
    sections: { move: 'SWINGING', camera: 'CAMERA', video: 'GRAPHICS', audio: 'SOUND' },
  },
  controls: {
    title: 'CONTROLS',
    keyboard: 'KEYBOARD AND MOUSE',
    gamepad: 'GAMEPAD',
    pressKey: 'Press a key',
    padRows: [
      ['Left stick', 'Move'],
      ['Right stick', 'Look'],
      ['RT / R2 (hold)', 'Web at the crosshair and swing, parkour run, wall run'],
      ['A / Cross', 'Jump (hold to go higher), swing-jump, web wings'],
      ['X / Square', 'Attack. In the air with nobody near: air trick'],
      ['RB / R1', 'Web shot'],
      ['LB / L1', 'Tap: use gadget. Hold: gadget wheel'],
      ['R3', 'Finisher (tap), heal (hold)'],
      ['LT + RT / L2 + R2', 'Web zip'],
      ['Y / Triangle', 'Hang on the web (stick up and down to climb), again to let go'],
      ['B / Circle (hold)', 'Dive, or rappel down a web'],
      ['D-pad up', 'Spider-sense scan'],
      ['D-pad left', 'Photo'],
      ['D-pad right', 'Air trick'],
      ['D-pad down', 'Next radio line'],
      ['Start / Options', 'Pause'],
      ['Back / Share', 'City map'],
    ],
  },
};
