// The playable roster (spec section 13): every character, how they move (a mover archetype), how
// they look (a painted suit or an outfit, plus gear built from code), their mass and parameter
// changes, and their special on the web button. Villain models are the same ones the bosses use.

// suit: colours for the hero suit shader (style as in progression SUITS). outfit: a look for the
// outfit shader (enemyModel FACTIONS format, plus pattern). gear: ids built in roster/build.js.
export const ROSTER = [
  { id: 'peter', name: 'Spider-Man', kind: 'hero', body: 'm', suitId: 'classic', mover: null, special: 'web', desc: 'Web swing, reel, zip, wall run, web wings. The full combo set and every gadget.' },
  { id: 'miles', name: 'Miles Morales', kind: 'hero', body: 'm', scale: [0.97, 0.97, 0.97], suit: { style: 0, red: 0x16161c, blue: 0x16161c, black: 0xd02030, lens: 0xf4f6fb, model: 'miles' }, mover: null, special: 'venomBlast', desc: 'Web swing like Peter. Venom blast shocks a crowd; camouflage hides him.' },
  { id: 'gwen', name: 'Spider-Gwen', kind: 'hero', body: 'f', suit: { style: 0, red: 0xf4f4f6, blue: 0x1a1a22, black: 0xe050a0, lens: 0x2a2a30, model: 'ghost' }, mover: null, tune: { airTurn: 0.6, airAccel: 3 }, special: 'kick', desc: 'Web swing with sharper air control. Fast kicks and web yank combos.' },
  { id: '2099', name: 'Spider-Man 2099', kind: 'hero', body: 'm', suitId: '2099', gear: ['cape2099'], mover: null, tune: { glideRatio: 1.5 }, special: 'talons', desc: 'Web swing and a cape that glides far further. Talon slashes.' },
  { id: 'noir', name: 'Spider-Man Noir', kind: 'hero', body: 'm', suitId: 'noir', mover: null, tune: { webMax: -20 }, special: 'smoke', desc: 'Shorter webs, the best stealth. Silent takedowns and smoke.' },
  { id: 'blackcat', name: 'Black Cat', kind: 'hero', body: 'f', outfit: { jacket: 0x14141a, pants: 0x14141a, shoes: 0x14141a, skin: 0.1, head: 0, hat: 0xf4f4f6, accent: 0xf4f4f6, pattern: 0 }, gear: ['hairWhite', 'fur'], mover: 'grappler', moverOpts: { cooldown: 1.2 }, special: 'claws', desc: 'One grapple line on a short cooldown and big acrobatics. Claws and bad-luck trips.' },
  { id: 'venom', name: 'Venom', kind: 'villain', body: 'm', scale: [1.32, 1.24, 1.3], suit: { style: 7, red: 0x0e0d16, blue: 0x0e0d16, black: 0xf4f6fb, lens: 0xf4f6fb }, gear: ['tendrils'], mover: null, mass: 110, tune: { zipSpeed: 10, winchSpeed: 4 }, special: 'tendril', desc: 'Symbiote swing: a heavier body and a stronger pull. Tendril grabs and a stunning roar.' },
  { id: 'vulture', name: 'Vulture', kind: 'villain', body: 'm', outfit: { jacket: 0x3f6a3a, pants: 0x2f5030, shoes: 0x1a1a1a, skin: 0.25, head: 5, hat: 0x1a1a1a, accent: 0xc8b070, pattern: 0 }, gear: ['wings', 'collar'], mover: 'flyer', special: 'feathers', desc: 'Flies on a wing harness: thrust, lift and drag. Dive talons and feather darts.' },
  { id: 'goblin', name: 'Green Goblin', kind: 'villain', body: 'm', outfit: { jacket: 0x6a3a8a, pants: 0x3a7a3a, shoes: 0x6a3a8a, skin: -2, head: 2, hat: 0x4a8a3a, accent: 0xf2c230, pattern: 4 }, gear: ['glider', 'goblinEars'], mover: 'glider', special: 'pumpkin', desc: 'A jet glider: thrust, aero and hover jets on fuel. Pumpkin bombs and razor bats.' },
  { id: 'ock', name: 'Doctor Octopus', kind: 'villain', body: 'm', scale: [1.08, 1.0, 1.08], outfit: { jacket: 0x4a6a3a, pants: 0x3a3a30, shoes: 0x2a2018, skin: 0.3, head: 0, hat: 0x2a1a10, accent: 0xd8c040, shades: 1, pattern: 0 }, gear: ['tentacles'], mover: 'tentacleWalker', special: 'tentacleSlam', desc: 'Four arms walk and climb any surface and haul him along. Tentacle slams and car throws.' },
  { id: 'electro', name: 'Electro', kind: 'villain', body: 'm', outfit: { jacket: 0x2a8a4a, pants: 0x2a8a4a, shoes: 0xf2d030, skin: -2, head: 2, hat: 0x2a8a4a, accent: 0xf2e040, pattern: 2 }, gear: ['starMask', 'krackle'], mover: 'cableRider', special: 'lightning', desc: 'Rides a magnetic pull to anything metal and shoves off it. Lightning arcs and overload.' },
  { id: 'rhino', name: 'Rhino', kind: 'villain', body: 'm', scale: [1.5, 1.32, 1.45], outfit: { jacket: 0x8a8f96, pants: 0x7a7f86, shoes: 0x6a6f76, skin: -2, head: 3, hat: 0x8a8f96, accent: 0x6a6f76, pattern: 4 }, gear: ['horn'], mover: 'heavy', moverOpts: { charge: 20, run: 8 }, mass: 320, special: 'charge', desc: 'Huge mass and momentum, a charge that flattens anything. Cannot climb.' },
  { id: 'lizard', name: 'Lizard', kind: 'villain', body: 'm', scale: [1.12, 1.08, 1.12], outfit: { jacket: 0xf0f0ea, pants: 0x4a8a3a, shoes: 0x4a8a3a, skin: -3, head: 6, hat: 0x4a8a3a, accent: 0x3a6a2a, pattern: 3 }, gear: ['tail', 'snout'], mover: 'climber', special: 'tailSwipe', desc: 'Climbs any surface and pounces off it. Tail swipes, bites and a roar.' },
  { id: 'scorpion', name: 'Scorpion', kind: 'villain', body: 'm', outfit: { jacket: 0x3a7a3a, pants: 0x3a7a3a, shoes: 0x2a4a2a, skin: -2, head: 3, hat: 0x3a7a3a, accent: 0x9ab040, pattern: 4 }, gear: ['stingerTail'], mover: 'grappler', moverOpts: { cooldown: 0.8 }, special: 'sting', desc: 'The tail is a rigid grapple to vault and pivot on, and he climbs walls. Sting and acid.' },
  { id: 'shocker', name: 'Shocker', kind: 'villain', body: 'm', outfit: { jacket: 0xd8b030, pants: 0x8a6030, shoes: 0x6a4020, skin: -2, head: 2, hat: 0x8a6030, accent: 0x6a4020, pattern: 1 }, gear: ['gauntlets'], mover: 'recoilJumper', special: 'vibro', desc: 'Vibro blasts push him the other way: blast down to jump, back to fly forward.' },
  { id: 'sandman', name: 'Sandman', kind: 'villain', body: 'm', scale: [1.1, 1.04, 1.1], outfit: { jacket: 0x3a8a4a, pants: 0x8a6a4a, shoes: 0x4a3a2a, skin: 0.3, head: 0, hat: 0x3a2a1a, accent: 0x1a1a1a, pattern: 5 }, gear: [], mover: 'sandSurfer', special: 'sandFist', desc: 'Surfs the street on a wave of sand and launches on sand pillars. Grows into a giant.' },
  { id: 'mysterio', name: 'Mysterio', kind: 'villain', body: 'm', outfit: { jacket: 0x3a8a4a, pants: 0x3a8a4a, shoes: 0x6a3a8a, skin: -2, head: 3, hat: 0xd8d8e0, accent: 0x6a3a8a, pattern: 0 }, gear: ['fishbowl', 'cape'], mover: 'hover', special: 'gas', desc: 'Hover boots on limited fuel and smoke cover. Illusion decoys and gas bombs.' },
  { id: 'kraven', name: 'Kraven', kind: 'villain', body: 'm', outfit: { jacket: 0xc89a4a, pants: 0xc89a4a, shoes: 0x3a2a1a, skin: 0.45, head: 0, hat: 0x2a1a10, accent: 0x1a1210, spots: 1, pattern: 0 }, gear: ['mane'], mover: 'grappler', moverOpts: { cooldown: 2.5 }, tune: { jumpSpeed: 14 }, special: 'spear', desc: 'Parkour and huge jumps, and a spear rope on a long cooldown. Spear, bolas and nets.' },
  { id: 'kingpin', name: 'Kingpin', kind: 'villain', body: 'm', scale: [1.6, 1.12, 1.5], outfit: { jacket: 0xf2f0e8, pants: 0xf2f0e8, shoes: 0x2a2a2a, skin: 0.25, head: 5, hat: 0x1a1a1a, accent: 0x6a2a6a, pattern: 0 }, gear: ['cane'], mover: 'heavy', moverOpts: { charge: 13, run: 7 }, mass: 180, special: 'cane', desc: 'A heavy brawler on foot who calls his helicopter and rides its rope ladder.' },
];

export const characterById = (id) => ROSTER.find((c) => c.id === id) ?? ROSTER[0];
